name: Certora API

on:
  workflow_dispatch:
    inputs:
      command:
        required: true
        description: |
          The Certora API command to execute. Options are:
          - `cancel <group_id>`: Cancel all jobs in the specified group.
          - `refresh <group_id>`: Refresh the status of all jobs in the specified group.

permissions:
  contents: read
  id-token: write

jobs:
  certora-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: Certora/certora-run-action/api@b202d974fbd137bd9190dcacd35a5a723c8fa68b # main
        with:
          certora-command: ${{ github.event.inputs.command }}
          server: production
